# Generated by Django 4.2.1 on 2023-06-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
